// 中英文食材映射表
const foodNameMap = {
    '苹果': 'apple',
        '香蕉': 'banana',
            '鸡肉': 'chicken',
                '米饭': 'rice',
                    '牛肉': 'beef',
                        '鸡蛋': 'egg',
                            '牛奶': 'milk',
                                '面包': 'bread',
                                    '鱼': 'fish',
                                        '土豆': 'potato',
                                            '番茄': 'tomato',
                                                '黄瓜': 'cucumber',
                                                    '胡萝卜': 'carrot',
                                                        '洋葱': 'onion',
                                                            '青椒': 'green pepper',
                                                                '菠菜': 'spinach',
                                                                    '白菜': 'cabbage',
                                                                        '芹菜': 'celery',
                                                                            '南瓜': 'pumpkin',
                                                                                '红薯': 'sweet potato',
                                                                                    '玉米': 'corn',
                                                                                        '豆腐': 'tofu',
                                                                                            '虾': 'shrimp',
                                                                                                '蟹': 'crab',
                                                                                                    '猪肉': 'pork',
                                                                                                        '羊肉': 'lamb',
                                                                                                            '鸭肉': 'duck',
                                                                                                                '火鸡': 'turkey',
                                                                                                                    '火腿': 'ham',
                                                                                                                        '香肠': 'sausage',
                                                                                                                            '奶酪': 'cheese',
                                                                                                                                '黄油': 'butter',
                                                                                                                                    '酸奶': 'yogurt',
                                                                                                                                        '冰淇淋': 'ice cream',
                                                                                                                                            '巧克力': 'chocolate',
                                                                                                                                                '蜂蜜': 'honey',
                                                                                                                                                    '花生': 'peanut',
                                                                                                                                                        '核桃': 'walnut',
                                                                                                                                                            '杏仁': 'almond',
                                                                                                                                                                '腰果': 'cashew',
                                                                                                                                                                    '葡萄': 'grape',
                                                                                                                                                                        '橙子': 'orange',
                                                                                                                                                                            '柠檬': 'lemon',
                                                                                                                                                                                '草莓': 'strawberry',
                                                                                                                                                                                    '蓝莓': 'blueberry',
                                                                                                                                                                                        '西瓜': 'watermelon',
                                                                                                                                                                                            '菠萝': 'pineapple',
                                                                                                                                                                                                '芒果': 'mango',
                                                                                                                                                                                                    '桃子': 'peach',
                                                                                                                                                                                                        '梨': 'pear',
                                                                                                                                                                                                            '李子': 'plum',
                                                                                                                                                                                                                '石榴': 'pomegranate',
                                                                                                                                                                                                                    '椰子': 'coconut',
                                                                                                                                                                                                                        '燕麦': 'oat',
                                                                                                                                                                                                                            '小麦': 'wheat',
                                                                                                                                                                                                                                '大麦': 'barley',
                                                                                                                                                                                                                                    '荞麦': 'buckwheat',
                                                                                                                                                                                                                                        '绿豆': 'mung bean',
                                                                                                                                                                                                                                            '红豆': 'red bean',
                                                                                                                                                                                                                                                '黑豆': 'black bean',
                                                                                                                                                                                                                                                    '扁豆': 'lentil',
                                                                                                                                                                                                                                                        '鹰嘴豆': 'chickpea',
                                                                                                                                                                                                                                                            '蘑菇': 'mushroom',
                                                                                                                                                                                                                                                                '金针菇': 'enoki mushroom',
                                                                                                                                                                                                                                                                    '香菇': 'shiitake mushroom',
                                                                                                                                                                                                                                                                        '木耳': 'wood ear mushroom',
                                                                                                                                                                                                                                                                            '海带': 'kelp',
                                                                                                                                                                                                                                                                                '紫菜': 'seaweed',
                                                                                                                                                                                                                                                                                    '虾米': 'dried shrimp',
                                                                                                                                                                                                                                                                                        '鱼丸': 'fish ball',
                                                                                                                                                                                                                                                                                            '牛肉丸': 'beef ball',
                                                                                                                                                                                                                                                                                                '饺子': 'dumpling',
                                                                                                                                                                                                                                                                                                    '面条': 'noodle',
                                                                                                                                                                                                                                                                                                        '意大利面': 'pasta',
                                                                                                                                                                                                                                                                                                            '披萨': 'pizza',
                                                                                                                                                                                                                                                                                                                '汉堡': 'hamburger',
                                                                                                                                                                                                                                                                                                                    '热狗': 'hot dog',
                                                                                                                                                                                                                                                                                                                        '三明治': 'sandwich',
                                                                                                                                                                                                                                                                                                                            '寿司': 'sushi',
                                                                                                                                                                                                                                                                                                                                '酱油': 'soy sauce',
                                                                                                                                                                                                                                                                                                                                    '醋': 'vinegar',
                                                                                                                                                                                                                                                                                                                                        '盐': 'salt',
                                                                                                                                                                                                                                                                                                                                            '糖': 'sugar',
                                                                                                                                                                                                                                                                                                                                                '胡椒': 'pepper',
                                                                                                                                                                                                                                                                                                                                                    '辣椒': 'chili',
                                                                                                                                                                                                                                                                                                                                                        '大蒜': 'garlic',
                                                                                                                                                                                                                                                                                                                                                            '姜': 'ginger',
                                                                                                                                                                                                                                                                                                                                                                '葱': 'scallion',
                                                                                                                                                                                                                                                                                                                                                                    '香菜': 'coriander',
                                                                                                                                                                                                                                                                                                                                                                        '薄荷': 'mint',
                                                                                                                                                                                                                                                                                                                                                                            '迷迭香': 'rosemary',
                                                                                                                                                                                                                                                                                                                                                                                '百里香': 'thyme',
                                                                                                                                                                                                                                                                                                                                                                                    '肉桂': 'cinnamon',
                                                                                                                                                                                                                                                                                                                                                                                        '香草': 'vanilla',
                                                                                                                                                                                                                                                                                                                                                                                            '咖喱': 'curry',
                                                                                                                                                                                                                                                                                                                                                                                                '橄榄油': 'olive oil',
                                                                                                                                                                                                                                                                                                                                                                                                    '芝麻油': 'sesame oil',
                                                                                                                                                                                                                                                                                                                                                                                                        '花生油': 'peanut oil',
                                                                                                                                                                                                                                                                                                                                                                                                            '椰子油': 'coconut oil',
                                                                                                                                                                                                                                                                                                                                                                                                                '红酒': 'red wine',
                                                                                                                                                                                                                                                                                                                                                                                                                    '啤酒': 'beer',
                                                                                                                                                                                                                                                                                                                                                                                                                        '绿茶': 'green tea',
                                                                                                                                                                                                                                                                                                                                                                                                                            '咖啡': 'coffee',
                                                                                                                                                                                                                                                                                                                                                                                                                                '果汁': 'juice',
                                                                                                                                                                                                                                                                                                                                                                                                                                    '可乐': 'cola'
                                                                                                                                                                                                                                                                                                                                                                                                                                    };

                                                                                                                                                                                                                                                                                                                                                                                                                                    document.getElementById('search-button').addEventListener('click', async () => {
                                                                                                                                                                                                                                                                                                                                                                                                                                        const foodName = document.getElementById('food-input').value;
                                                                                                                                                                                                                                                                                                                                                                                                                                            if (foodName) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                    const englishName = foodNameMap[foodName]; // 从映射表中获取英文名称
                                                                                                                                                                                                                                                                                                                                                                                                                                                            if (englishName) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        const calories = await getFoodCalories(englishName); // 使用英文名称查询
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    displayResult(calories);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            } else {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        displayResult(null);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    });

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    // 获取食物热量
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    async function getFoodCalories(foodName) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        const apiKey = '62dc9f37f96b4b7b8e545908396e833e'; // 你的 Spoonacular API 密钥
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            const encodedFoodName = encodeURIComponent(foodName); // 对英文名称进行编码
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                const apiUrl = `https://api.spoonacular.com/food/ingredients/search?query=${encodedFoodName}&apiKey=${apiKey}`;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    console.log('API URL:', apiUrl); // 打印 URL 以检查是否正确

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        try {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                const response = await fetch(apiUrl);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        const data = await response.json();

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                console.log('API Response:', data); // 打印 API 响应数据

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        if (data.results && data.results.length > 0) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    const ingredientId = data.results[0].id; // 获取第一个匹配食材的 ID
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                const nutritionData = await getNutritionData(ingredientId, apiKey);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            return nutritionData;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    } else {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                console.error('未找到匹配的食物');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            return null;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        } catch (error) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                console.error('获取数据失败:', error);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        return null;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            // 获取营养数据
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            async function getNutritionData(ingredientId, apiKey) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                const apiUrl = `https://api.spoonacular.com/food/ingredients/${ingredientId}/information?amount=100&unit=grams&apiKey=${apiKey}`;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    console.log('Nutrition API URL:', apiUrl); // 打印营养数据 API 的 URL

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        try {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                const response = await fetch(apiUrl);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        const data = await response.json();

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                console.log('Nutrition API Response:', data); // 打印营养数据 API 的响应

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        if (data.nutrition && data.nutrition.nutrients) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    const calories = data.nutrition.nutrients.find(nutrient => nutrient.name === 'Calories');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                return calories;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        } else {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    console.error('未找到营养数据');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                return null;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            } catch (error) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    console.error('获取营养数据失败:', error);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            return null;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                // 显示结果
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                function displayResult(calories) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    const resultElement = document.getElementById('result');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        if (calories) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                resultElement.textContent = `每100克的热量: ${calories.amount} ${calories.unit}`;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    } else {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            resultElement.textContent = '未找到该食物的热量信息。';
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }